---
# file: roles/apache/tasks/main.yml

- name: Install httpd package
  yum: name=httpd state=latest
  sudo: yes

- name: Install Git
  yum: name=git state=latest
  sudo: yes

- name: create known_hosts file
  file: path=/home/ec2-user/.ssh/known_hosts state=touch mode=0644

- name: ensure github.com is a known host
  known_hosts: path='/home/ec2-user/.ssh/known_hosts'
           name='github.com'
           key="{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"

- name: Clone Git repo of demo website
  git: >
    repo="{{ git_repo }}"
    version=master
    dest=/var/www/html
    accept_hostkey=True

- name: Starting http service
  service: name=httpd state=started
  sudo: yes
