---
# file: site.yml

- name: Provision EC2 instance
  hosts: localhost
  sudo: False
  user: ec2-user
  gather_facts: False
  serial: 1
  tags: provision
  vars:
        key_name: "AWSKeypair2"
        instance_type: m1.small
        security_group: default
        image: ami-95e33ce6
        region: eu-west-1
        vpc_subnet_id: subnet-ed98ca88
        instance_name: ansible
        zone: demosiili.com
  roles:
    - ec2

- name: Configure EC2 instance
  hosts: webserver
  sudo: True
  user: ec2-user
  gather_facts: True
  tags: configure
  roles:
    - apache
